Update (macOS) Hands-Off Authorization - UI version
macOS sript for authorizing Live for all users with token authorization

diff --git a/(macOS) Hands-Off Authorization b/(macOS) Hands-Off Authorization
--- a/(macOS) Hands-Off Authorization
+++ b/(macOS) Hands-Off Authorization
@@ -1,4 +1,4 @@
-#!/usr/bin/env bash
+#!/bin/bash
 
 # Use osascript to show a dialog box for user input
 
@@ -22,35 +22,44 @@ osascript -e 'tell app "System Events" to display dialog "Error: Both version an
   exit 1
 fi
 
-# Print the variables (for testing purposes)
+# Print the variables to validate the input
 
 echo "VERSION: $VERSION"
 echo "TOKEN: $TOKEN"
 
 osascript -e 'tell app "System Events" to display dialog "Thanks. Live '$VERSION' will be authorized for all users on this machine. Your token '$TOKEN' will be used to authorize Live. Please click OK, then click in the Terminal window and enter your Administrator password."'
 
-# Create shared Unlock folder
+# Create shared Unlock folder with empty Unlock.json file
 
-sudo mkdir -p /Library/Application Support/Ableton/Live $VERSION/Unlock/
-
-# Create empty Unlock.json file
-
-sudo touch /Library/Application Support/Ableton/Live $VERSION/Unlock/Unlock.json
+mkdir -p "/Library/Application Support/Ableton/Live ${VERSION}/Unlock/"
+touch "/Library/Application Support/Ableton/Live ${VERSION}/Unlock/Unlock.json"
+chmod a+rw  "/Library/Application Support/Ableton/Live ${VERSION}/Unlock/Unlock.json"
+rm -f "/Library/Application Support/Ableton/Live ${VERSION}/Unlock/Unlock.cfg" 2>/dev/null
 
 # Create shared preferences folder and add Options.txt entries
 
-sudo mkdir -p /Library/Preferences/Ableton/Live $VERSION/
-echo "-_DisableAutoUpdates" | sudo tee /Library/Preferences/Ableton/Live $VERSION/Options.txt
-#wtf is going wrong here
+mkdir -p /Library/Preferences/Ableton/Live ${VERSION}/
+chmod a+rw "/Library/Preferences/Ableton/Live ${VERSION}/"
 
+# Add Options.txy entry
+echo "-_DisableAutoUpdates" > "/Library/Preferences/Ableton/Live ${VERSION}/Options.txt"
+
+# This bit will be for adding proxy awareness
 # echo "-HttpsProxy=xxx.xxx.xx.x" | sudo tee -a "/Library/Preferences/Ableton/Live $VERSION/Options.txt"
 
-# Add authorization token
+# Add authorization token, launch Live
 
-echo $TOKEN | sudo tee /Applications/Ableton Live 12 Suite.app/Contents/MacOS/Live --authorization-token=$TOKEN
+"/Applications/Ableton Live 12 ${EDITION}.app/Contents/MacOS/Live --authorization-token=${TOKEN}
 
-# Launch Live so it authorizes with the token, wait then close
+# Capture the exit code
+LIVE_EXIT_CODE=$?
 
-open -a "Ableton Live 12 Suite"
-sleep 30
-osascript -e 'quit app "Ableton Live 12 Suite"'
+ Check the exit code
+if [ $LIVE_EXIT_CODE -ne 0 ]; then
+    echo "${EXECUTABLE} exited with code ${LIVE_EXIT_CODE}"
+    exit $LIVE_EXIT_CODE
+else
+    echo "${EXECUTABLE} completed successfully."
+    exit 0
+fi
+
